In [2]:
import pandas as pd

In [3]:
pd.read_csv("E:\PM AI Program\weather.csv")

<>:1: SyntaxWarning: "\P" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\P"? A raw string is also an option.
<>:1: SyntaxWarning: "\P" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\P"? A raw string is also an option.
C:\Users\DELL\AppData\Local\Temp\ipykernel_9792\2125555308.py:1: SyntaxWarning: "\P" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\P"? A raw string is also an option.
  pd.read_csv("E:\PM AI Program\weather.csv")

,MIN temp (deg Celcius),Location,Time,Wind,MAX temp (deg Celcius),Description,Precipitation (in %),Date,Other Details,Humidity (in %),Day
0,22,"Bharsul, India 10-day Weather",23:04 IST,NE 2 km/h,--,Clear,0,18 OCT,Generally clear. Low 22ºC. Winds NE and variable.,48,Tonight
1,22,"Bharsul, India 10-day Weather",23:04 IST,NNW 7 km/h,36,Mostly Sunny,0,19 OCT,Generally clear. High 36ºC. Winds NNW and vari...,29,Fri
2,22,"Bharsul, India 10-day Weather",23:04 IST,SSW 5 km/h,35,Sunny,0,20 OCT,Generally clear. High 35ºC. Winds SSW and vari...,29,Sat
3,21,"Bharsul, India 10-day Weather",23:04 IST,WSW 9 km/h,36,Sunny,0,21 OCT,Generally clear. High 36ºC. Winds WSW and vari...,32,Sun
4,21,"Bharsul, India 10-day Weather",23:04 IST,N 9 km/h,35,Sunny,0,22 OCT,Generally clear. High 35ºC. Winds N and variable.,31,Mon
5,21,"Bharsul, India 10-day Weather",23:04 IST,W 8 km/h,35,Sunny,0,23 OCT,Generally clear. High 35ºC. Winds W and variable.,29,Tue
6,21,"Bharsul, India 10-day Weather",23:04 IST,SSE 7 km/h,34,Mostly Sunny,0,24 OCT,Generally clear. High 34ºC. Winds SSE and vari...,28,Wed
7,20,"Bharsul, India 10-day Weather",23:04 IST,SSW 9 km/h,34,Mostly Sunny,0,25 OCT,Generally clear. High 34ºC. Winds SSW and vari...,27,Thu
8,20,"Bharsul, India 10-day Weather",23:04 IST,E 7 km/h,34,Mostly Sunny,0,26 OCT,Generally clear. High 34ºC. Winds E and variable.,29,Fri
9,19,"Bharsul, India 10-day Weather",23:04 IST,NE 10 km/h,34,Sunny,0,27 OCT,Generally clear. High 34ºC. Winds NE at 10 to ...,30,Sat
10,19,"Bharsul, India 10-day Weather",23:04 IST,NE 7 km/h,33,Sunny,0,28 OCT,Generally clear. High 33ºC. Winds NE and varia...,28,Sun
11,19,"Bharsul, India 10-day Weather",23:04 IST,ENE 6 km/h,33,Sunny,0,29 OCT,Generally clear. High 33ºC. Winds ENE and vari...,26,Mon
12,19,"Bharsul, India 10-day Weather",23:04 IST,E 6 km/h,33,Sunny,0,30 OCT,Generally clear. High 33ºC. Winds E and variable.,27,Tue
13,19,"Bharsul, India 10-day Weather",23:04 IST,ESE 5 km/h,33,Sunny,0,31 OCT,Generally clear. High 33ºC. Winds ESE and vari...,27,Wed
14,19,"Bharsul, India 10-day Weather",23:04 IST,NNW 5 km/h,33,Sunny,0,1 NOV,Generally clear. High 33ºC. Winds NNW and vari...,28,Thu
15,MIN temp (deg Celcius),Location,Time,Wind,MAX temp (deg Celcius),Description,Precipitation (in %),Date,Other Details,Humidity (in %),Day
16,22,"Bharsul, India 10-day Weather",23:04 IST,NE 2 km/h,--,Clear,0,18 OCT,Generally clear. Low 22ºC. Winds NE and variable.,48,Tonight
17,22,"Bharsul, India 10-day Weather",23:04 IST,NNW 7 km/h,36,Mostly Sunny,0,19 OCT,Generally clear. High 36ºC. Winds NNW and vari...,29,Fri
18,22,"Bharsul, India 10-day Weather",23:04 IST,SSW 5 km/h,35,Sunny,0,20 OCT,Generally clear. High 35ºC. Winds SSW and vari...,29,Sat
19,21,"Bharsul, India 10-day Weather",23:04 IST,WSW 9 km/h,36,Sunny,0,21 OCT,Generally clear. High 36ºC. Winds WSW and vari...,32,Sun
20,21,"Bharsul, India 10-day Weather",23:04 IST,N 9 km/h,35,Sunny,0,22 OCT,Generally clear. High 35ºC. Winds N and variable.,31,Mon
21,21,"Bharsul, India 10-day Weather",23:04 IST,W 8 km/h,35,Sunny,0,23 OCT,Generally clear. High 35ºC. Winds W and variable.,29,Tue
22,21,"Bharsul, India 10-day Weather",23:04 IST,SSE 7 km/h,34,Mostly Sunny,0,24 OCT,Generally clear. High 34ºC. Winds SSE and vari...,28,Wed
23,20,"Bharsul, India 10-day Weather",23:04 IST,SSW 9 km/h,34,Mostly Sunny,0,25 OCT,Generally clear. High 34ºC. Winds SSW and vari...,27,Thu
24,20,"Bharsul, India 10-day Weather",23:04 IST,E 7 km/h,34,Mostly Sunny,0,26 OCT,Generally clear. High 34ºC. Winds E and variable.,29,Fri
25,19,"Bharsul, India 10-day Weather",23:04 IST,NE 10 km/h,34,Sunny,0,27 OCT,Generally clear. High 34ºC. Winds NE at 10 to ...,30,Sat
26,19,"Bharsul, India 10-day Weather",23:04 IST,NE 7 km/h,33,Sunny,0,28 OCT,Generally clear. High 33ºC. Winds NE and varia...,28,Sun
27,19,"Bharsul, India 10-day Weather",23:04 IST,ENE 6 km/h,33,Sunny,0,29 OCT,Generally clear. High 33ºC. Winds ENE and vari...,26,Mon
28,19,"Bharsul, India 10-day Weather",23:04 IST,E 6 km/h,33,Sunny,0,30 OCT,Generally clear. High 33ºC. Winds E and variable.,27,Tue
29,19,"Bharsul, India 10-day Weather",23:04 IST,ESE 5 km/h,33,Sunny,0,31 OCT,Generally clear. High 33ºC. Winds ESE and vari...,27,Wed
30,19,"Bharsul, India 10-day Weather",23:04 IST,NNW 5 km/h,33,Sunny,0,1 NOV,Generally clear. High 33ºC. Winds NNW and vari...,28,Thu

In [4]:
df= pd.read_csv("E:\PM AI Program\weather.csv")

<>:1: SyntaxWarning: "\P" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\P"? A raw string is also an option.
<>:1: SyntaxWarning: "\P" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\P"? A raw string is also an option.
C:\Users\DELL\AppData\Local\Temp\ipykernel_9792\1788717598.py:1: SyntaxWarning: "\P" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\P"? A raw string is also an option.
  df= pd.read_csv("E:\PM AI Program\weather.csv")

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   MIN temp (deg Celcius)  31 non-null     str
 1   Location                31 non-null     str
 2   Time                    31 non-null     str
 3   Wind                    31 non-null     str
 4   MAX temp (deg Celcius)  31 non-null     str
 5   Description             31 non-null     str
 6   Precipitation (in %)    31 non-null     str
 7   Date                    31 non-null     str
 8   Other Details           31 non-null     str
 9   Humidity (in %)         31 non-null     str
 10  Day                     31 non-null     str
dtypes: str(11)
memory usage: 2.8 KB

In [6]:
df.describe()

,MIN temp (deg Celcius),Location,Time,Wind,MAX temp (deg Celcius),Description,Precipitation (in %),Date,Other Details,Humidity (in %),Day
count,31,31,31,31,31,31,31,31,31,31,31
unique,5,2,2,16,6,4,2,16,16,9,9
top,19,"Bharsul, India 10-day Weather",23:04 IST,NE 2 km/h,33,Sunny,0,18 OCT,Generally clear. Low 22ºC. Winds NE and variable.,29,Fri
freq,12,30,30,2,10,20,30,2,2,8,4

In [7]:
print(df.isnull().sum().sum())  #shows all zeros togeather

0

In [8]:
print(df.notnull().sum().sum())

341

In [9]:
print(df.isnull().sum())  #show null value colume by colume

MIN temp (deg Celcius)    0
Location                  0
Time                      0
Wind                      0
MAX temp (deg Celcius)    0
Description               0
Precipitation (in %)      0
Date                      0
Other Details             0
Humidity (in %)           0
Day                       0
dtype: int64

In [10]:
df.dtypes

MIN temp (deg Celcius)    str
Location                  str
Time                      str
Wind                      str
MAX temp (deg Celcius)    str
Description               str
Precipitation (in %)      str
Date                      str
Other Details             str
Humidity (in %)           str
Day                       str
dtype: object

In [12]:
print(df['Location'].unique())

<StringArray>
['Bharsul, India 10-day Weather', 'Location']
Length: 2, dtype: str

In [16]:
df.nunique()

MIN temp (deg Celcius)     5
Location                   2
Time                       2
Wind                      16
MAX temp (deg Celcius)     6
Description                4
Precipitation (in %)       2
Date                      16
Other Details             16
Humidity (in %)            9
Day                        9
dtype: int64

In [17]:
df.count()

MIN temp (deg Celcius)    31
Location                  31
Time                      31
Wind                      31
MAX temp (deg Celcius)    31
Description               31
Precipitation (in %)      31
Date                      31
Other Details             31
Humidity (in %)           31
Day                       31
dtype: int64

In [18]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16     True
17     True
18     True
19     True
20     True
21     True
22     True
23     True
24     True
25     True
26     True
27     True
28     True
29     True
30     True
dtype: bool

In [21]:
df["Date"]

0     18 OCT
1     19 OCT
2     20 OCT
3     21 OCT
4     22 OCT
5     23 OCT
6     24 OCT
7     25 OCT
8     26 OCT
9     27 OCT
10    28 OCT
11    29 OCT
12    30 OCT
13    31 OCT
14     1 NOV
15      Date
16    18 OCT
17    19 OCT
18    20 OCT
19    21 OCT
20    22 OCT
21    23 OCT
22    24 OCT
23    25 OCT
24    26 OCT
25    27 OCT
26    28 OCT
27    29 OCT
28    30 OCT
29    31 OCT
30     1 NOV
Name: Date, dtype: str

In [23]:
df["Location"]

0     Bharsul, India 10-day Weather
1     Bharsul, India 10-day Weather
2     Bharsul, India 10-day Weather
3     Bharsul, India 10-day Weather
4     Bharsul, India 10-day Weather
5     Bharsul, India 10-day Weather
6     Bharsul, India 10-day Weather
7     Bharsul, India 10-day Weather
8     Bharsul, India 10-day Weather
9     Bharsul, India 10-day Weather
10    Bharsul, India 10-day Weather
11    Bharsul, India 10-day Weather
12    Bharsul, India 10-day Weather
13    Bharsul, India 10-day Weather
14    Bharsul, India 10-day Weather
15                         Location
16    Bharsul, India 10-day Weather
17    Bharsul, India 10-day Weather
18    Bharsul, India 10-day Weather
19    Bharsul, India 10-day Weather
20    Bharsul, India 10-day Weather
21    Bharsul, India 10-day Weather
22    Bharsul, India 10-day Weather
23    Bharsul, India 10-day Weather
24    Bharsul, India 10-day Weather
25    Bharsul, India 10-day Weather
26    Bharsul, India 10-day Weather
27    Bharsul, India 10-day Weather
28    Bharsul, India 10-day Weather
29    Bharsul, India 10-day Weather
30    Bharsul, India 10-day Weather
Name: Location, dtype: str

In [25]:
pd.read_csv("E:\PM AI Program\data.csv")

<>:1: SyntaxWarning: "\P" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\P"? A raw string is also an option.
<>:1: SyntaxWarning: "\P" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\P"? A raw string is also an option.
C:\Users\DELL\AppData\Local\Temp\ipykernel_9792\2613866395.py:1: SyntaxWarning: "\P" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\P"? A raw string is also an option.
  pd.read_csv("E:\PM AI Program\data.csv")

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0