In [62]:
import pandas as pd

In [63]:
df = pd.read_csv("E:\PM AI Program\TASKS\sales.csv")

<>:1: SyntaxWarning: "\P" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\P"? A raw string is also an option.
<>:1: SyntaxWarning: "\P" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\P"? A raw string is also an option.
C:\Users\DELL\AppData\Local\Temp\ipykernel_10476\2378932537.py:1: SyntaxWarning: "\P" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\P"? A raw string is also an option.
  df = pd.read_csv("E:\PM AI Program\TASKS\sales.csv")

# Data Reading Tasks:
1. Read the dataset from a CSV file into a pandas DataFrame

In [64]:
df

,order_id,date,region,product,category,customer_type,quantity,price,discount,sales
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590,0.09,4295.20
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262,0.18,429.68
2,3,2024-09-27,North,Phone,Accessories,New,5,512,0.09,2329.60
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485,0.09,441.35
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332,0.22,1812.72
...,...,...,...,...,...,...,...,...,...,...
495,496,2024-11-20,South,Mouse,Accessories,Returning,6,314,0.23,1450.68
496,497,2024-01-04,North,Phone,Accessories,Returning,9,369,0.23,2557.17
497,498,2024-01-16,South,Keyboard,Electronics,Returning,6,722,0.14,3725.52
498,499,2024-10-06,North,Phone,Accessories,Returning,2,1449,0.12,2550.24
499,500,2024-12-01,North,Monitor,Electronics,New,2,869,0.09,1581.58

2. Display the first 8 rows and check the basic structure of the dataset using .info()

In [65]:
print(df.head(8))
print(df.info())

   order_id        date region  product     category customer_type  quantity  \
0         1  2024-04-12   East   Laptop  Electronics     Returning         8
1         2  2024-12-14  South  Monitor  Accessories     Returning         2
2         3  2024-09-27  North    Phone  Accessories           New         5
3         4  2024-04-16   West    Mouse  Electronics     Returning         1
4         5  2024-03-12   West    Phone  Electronics     Returning         7
5         6  2024-07-07   West   Laptop  Electronics           New         8
6         7  2024-01-21   East    Mouse  Accessories     Returning         6
7         8  2024-04-12   West    Phone  Accessories     Returning         5

   price  discount     sales
0    590      0.09   4295.20
1    262      0.18    429.68
2    512      0.09   2329.60
3    485      0.09    441.35
4    332      0.22   1812.72
5   1480      0.01  11721.60
6    137      0.27    600.06
7   1117      0.26   4132.90
<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       500 non-null    int64
 1   date           500 non-null    str
 2   region         500 non-null    str
 3   product        500 non-null    str
 4   category       500 non-null    str
 5   customer_type  500 non-null    str
 6   quantity       500 non-null    int64
 7   price          500 non-null    int64
 8   discount       500 non-null    float64
 9   sales          500 non-null    float64
dtypes: float64(2), int64(3), str(5)
memory usage: 39.2 KB
None

3. Get statistical summary of numerical columns using .describe()

In [66]:
df.describe()

         order_id    quantity        price   discount         sales
count  500.000000  500.000000   500.000000  500.00000    500.000000
mean   250.500000    4.968000   768.158000    0.14666   3333.059560
std    144.481833    2.569081   404.010497    0.08612   2693.185995
min      1.000000    1.000000    50.000000    0.00000     67.320000
25%    125.750000    3.000000   432.750000    0.08000   1120.867500
50%    250.500000    5.000000   742.000000    0.15000   2582.805000
75%    375.250000    7.000000  1094.500000    0.22000   4998.030000
max    500.000000    9.000000  1499.000000    0.30000  12700.800000

4. Check column names and rename any columns for better readability (e.g., rename 'order_id' to 'OrderID')

In [67]:
df.columns

Index(['order_id', 'date', 'region', 'product', 'category', 'customer_type',
       'quantity', 'price', 'discount', 'sales'],
      dtype='str')

In [68]:
df.rename(columns={'order_id': 'OrderID'})

,OrderID,date,region,product,category,customer_type,quantity,price,discount,sales
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590,0.09,4295.20
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262,0.18,429.68
2,3,2024-09-27,North,Phone,Accessories,New,5,512,0.09,2329.60
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485,0.09,441.35
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332,0.22,1812.72
...,...,...,...,...,...,...,...,...,...,...
495,496,2024-11-20,South,Mouse,Accessories,Returning,6,314,0.23,1450.68
496,497,2024-01-04,North,Phone,Accessories,Returning,9,369,0.23,2557.17
497,498,2024-01-16,South,Keyboard,Electronics,Returning,6,722,0.14,3725.52
498,499,2024-10-06,North,Phone,Accessories,Returning,2,1449,0.12,2550.24
499,500,2024-12-01,North,Monitor,Electronics,New,2,869,0.09,1581.58

# Data Cleaning Tasks:
5. Check for missing values in each column and handle them appropriately

In [69]:
df.isnull().sum()

order_id         0
date             0
region           0
product          0
category         0
customer_type    0
quantity         0
price            0
discount         0
sales            0
dtype: int64

6. Check for duplicate rows and remove any duplicates if found

In [70]:
df.drop_duplicates(inplace=True)
df

,order_id,date,region,product,category,customer_type,quantity,price,discount,sales
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590,0.09,4295.20
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262,0.18,429.68
2,3,2024-09-27,North,Phone,Accessories,New,5,512,0.09,2329.60
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485,0.09,441.35
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332,0.22,1812.72
...,...,...,...,...,...,...,...,...,...,...
495,496,2024-11-20,South,Mouse,Accessories,Returning,6,314,0.23,1450.68
496,497,2024-01-04,North,Phone,Accessories,Returning,9,369,0.23,2557.17
497,498,2024-01-16,South,Keyboard,Electronics,Returning,6,722,0.14,3725.52
498,499,2024-10-06,North,Phone,Accessories,Returning,2,1449,0.12,2550.24
499,500,2024-12-01,North,Monitor,Electronics,New,2,869,0.09,1581.58

7. Convert 'date' column to datetime format

In [71]:

df['date'] = pd.to_datetime(df['date'])
df

,order_id,date,region,product,category,customer_type,quantity,price,discount,sales
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590,0.09,4295.20
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262,0.18,429.68
2,3,2024-09-27,North,Phone,Accessories,New,5,512,0.09,2329.60
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485,0.09,441.35
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332,0.22,1812.72
...,...,...,...,...,...,...,...,...,...,...
495,496,2024-11-20,South,Mouse,Accessories,Returning,6,314,0.23,1450.68
496,497,2024-01-04,North,Phone,Accessories,Returning,9,369,0.23,2557.17
497,498,2024-01-16,South,Keyboard,Electronics,Returning,6,722,0.14,3725.52
498,499,2024-10-06,North,Phone,Accessories,Returning,2,1449,0.12,2550.24
499,500,2024-12-01,North,Monitor,Electronics,New,2,869,0.09,1581.58

8. Check data types of all columns and convert if necessary (e.g., ensure 'quantity' is int, 'price' is float)

In [72]:
df.dtypes
df.astype({'price':float})

,order_id,date,region,product,category,customer_type,quantity,price,discount,sales
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590.0,0.09,4295.20
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262.0,0.18,429.68
2,3,2024-09-27,North,Phone,Accessories,New,5,512.0,0.09,2329.60
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485.0,0.09,441.35
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332.0,0.22,1812.72
...,...,...,...,...,...,...,...,...,...,...
495,496,2024-11-20,South,Mouse,Accessories,Returning,6,314.0,0.23,1450.68
496,497,2024-01-04,North,Phone,Accessories,Returning,9,369.0,0.23,2557.17
497,498,2024-01-16,South,Keyboard,Electronics,Returning,6,722.0,0.14,3725.52
498,499,2024-10-06,North,Phone,Accessories,Returning,2,1449.0,0.12,2550.24
499,500,2024-12-01,North,Monitor,Electronics,New,2,869.0,0.09,1581.58

9. Standardize 'region' values (ensure consistent capitalization and remove extra spaces)

In [73]:
df['region'] = df['region'].str.strip().str.title()
print(df['region'])

0       East
1      South
2      North
3       West
4       West
       ...
495    South
496    North
497    South
498    North
499    North
Name: region, Length: 500, dtype: str

# Data Analysis Tasks:
10. Calculate total sales by region and find which region has the highest sales

In [74]:
df.groupby('region')['sales'].sum()

region
East     422023.71
North    509052.69
South    362158.72
West     373294.66
Name: sales, dtype: float64

12. Find the average discount given for each product category

In [75]:
df.groupby('category')['discount'].sum()

category
Accessories    35.36
Electronics    37.97
Name: discount, dtype: float64

13. Analyze customer ratings - calculate average rating by customer type (New vs Returning)

In [76]:
df.groupby('customer_type')['discount'].mean()

customer_type
New          0.140669
Returning    0.152146
Name: discount, dtype: float64

14. Find top 5 products by quantity sold

In [77]:
df.groupby('product')['quantity'].sum().sort_values(ascending=False).head(5)

product
Mouse       481
Laptop      449
Tablet      411
Keyboard    390
Phone       383
Name: quantity, dtype: int64

15. Calculate monthly sales trend by extracting month from date column (check pandas date time modules)

In [78]:
df.groupby(df['date'].dt.to_period('M'))['sales'].sum()

date
2024-01     98673.77
2024-02    131625.24
2024-03     70335.46
2024-04    150967.04
2024-05    176939.29
2024-06    155607.27
2024-07    128419.96
2024-08    194347.39
2024-09    157999.69
2024-10    131809.83
2024-11    118704.40
2024-12    151100.44
Freq: M, Name: sales, dtype: float64

16. Analyze discount impact on sales - compare average sales with and without discount

In [79]:
discount_impact = df.groupby(df['discount']> 0)['sales'].agg(['mean','count','sum']).round(3)
discount = df.groupby(df['discount'] > 0)['sales'].agg
discount_impact.index = ['no Discount', 'With Discount']
print(discount_impact)

                   mean  count         sum
no Discount    4165.846     13    54156.00
With Discount  3310.829    487  1612373.78

17. Find the most profitable product (highest total sales amount)

In [80]:
df.groupby('product')['sales'].sum().sort_values(ascending=False)

product
Laptop      317281.14
Mouse       299401.20
Monitor     281509.14
Tablet      262582.76
Keyboard    260675.81
Phone       245079.73
Name: sales, dtype: float64

18. Analyze customer behavior - compare purchase patterns between New and Returning customers

In [81]:
df.groupby('customer_type')[['quantity','sales','discount']].mean().round()

               quantity   sales  discount
customer_type
New                 5.0  3322.0       0.0
Returning           5.0  3343.0       0.0