In [1]:
import pandas as pd

# 1️⃣ Basic Data Exploration

1. LOAD DATASAT

In [2]:
df = pd.read_csv("E:\PM AI Program\TASKS\data.csv")

<>:1: SyntaxWarning: "\P" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\P"? A raw string is also an option.
<>:1: SyntaxWarning: "\P" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\P"? A raw string is also an option.
C:\Users\DELL\AppData\Local\Temp\ipykernel_10648\4186028876.py:1: SyntaxWarning: "\P" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\P"? A raw string is also an option.
  df = pd.read_csv("E:\PM AI Program\TASKS\data.csv")

2.FIRST FIVE ROW

In [3]:
df.head(5)

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

3.LAST FIVE ROWS

In [4]:
df.tail(5)

    Duration          Date  Pulse  Maxpulse  Calories
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

4. DATA SHAPE

In [5]:
df.shape

(32, 5)

5. Column names

In [6]:
df.columns

Index(['Duration', 'Date', 'Pulse', 'Maxpulse', 'Calories'], dtype='str')

6. Data types

In [7]:
df.dtypes

Duration      int64
Date            str
Pulse         int64
Maxpulse      int64
Calories    float64
dtype: object

7. Statistical summary

In [8]:
df.describe()

         Duration       Pulse    Maxpulse    Calories
count   32.000000   32.000000   32.000000   30.000000
mean    68.437500  103.500000  128.500000  304.680000
std     70.039591    7.832933   12.998759   66.003779
min     30.000000   90.000000  101.000000  195.100000
25%     60.000000  100.000000  120.000000  250.700000
50%     60.000000  102.500000  127.500000  291.200000
75%     60.000000  106.500000  132.250000  343.975000
max    450.000000  130.000000  175.000000  479.000000

8. Maximum Pulse

In [9]:
df["Pulse"].max()

np.int64(130)

9. Minimum duration

In [10]:
df["Duration"].min()

np.int64(30)

10. Average Calories

In [11]:
df["Calories"].mean()

np.float64(304.68)

## 2️⃣ Data Cleaning Tasks
11. Convert Date column to datetime

In [12]:
df["Date"] = pd.to_datetime(df["Date"], format="mixed")

12. Find missing values

In [13]:
df.isnull().sum()

Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    2
dtype: int64

13. Replace missing Calories with mean

In [14]:
df["Calories"].fillna(df["Calories"].mean(), inplace=True)

C:\Users\DELL\AppData\Local\Temp\ipykernel_10648\1871284254.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Calories"].fillna(df["Calories"].mean(), inplace=True)

0     409.10
1     479.00
2     340.00
3     282.40
4     406.00
5     300.00
6     374.00
7     253.30
8     195.10
9     269.00
10    329.30
11    250.70
12    250.70
13    345.30
14    379.30
15    275.00
16    215.20
17    300.00
18    304.68
19    323.00
20    243.00
21    364.20
22    282.00
23    300.00
24    246.00
25    334.50
26    250.00
27    241.00
28    304.68
29    280.00
30    380.30
31    243.00
Name: Calories, dtype: float64

14. Remove duplicate rows

In [15]:
df.drop_duplicates(inplace=True)

15. Fix incorrect Duration values (450 → 45)

In [16]:
df.loc[df["Duration"] == 450, "Duration"] = 45

16. Remove rows where Date is missing

In [17]:
df.dropna(subset=["Date"], inplace=True)

17. Fix date like "20201226"

In [18]:
df["Date"] = pd.to_datetime(df["Date"], format="mixed")

# 3️⃣ Data Selection Tasks
18. Duration greater than 60

In [19]:
df[df["Duration"] > 60]

Empty DataFrame
Columns: [Duration, Date, Pulse, Maxpulse, Calories]
Index: []

19. Pulse greater than 110

In [20]:
df[df["Pulse"] > 110]

    Duration       Date  Pulse  Maxpulse  Calories
1         60 2020-12-02    117       145     479.0
4         45 2020-12-05    117       148     406.0
23        60 2020-12-23    130       101     300.0

20. Calories greater than 350

In [21]:
df[df["Calories"] > 350]

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
4         45 2020-12-05    117       148     406.0
6         60 2020-12-07    110       136     374.0
14        60 2020-12-14    104       132     379.3
21        60 2020-12-21    108       131     364.2
30        60 2020-12-30    102       129     380.3

21. Pulse between 100 and 110

In [22]:
df[(df["Pulse"] >= 100) & (df["Pulse"] <= 110)]

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
2         60 2020-12-03    103       135     340.0
3         45 2020-12-04    109       175     282.4
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
7         45 2020-12-08    104       134     253.3
8         30 2020-12-09    109       133     195.1
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
17        60 2020-12-17    100       120     300.0
19        60 2020-12-19    103       123     323.0
21        60 2020-12-21    108       131     364.2
24        45 2020-12-24    105       132     246.0
25        60 2020-12-25    102       126     334.5
26        60 2020-12-26    100       120     250.0
28        60 2020-12-28    103       132       NaN
29        60 2020-12-29    100       132     280.0
30        60 2020-12-30    102       129     380.3

22. Only Duration and Calories columns

In [23]:
df[["Duration", "Calories"]]

    Duration  Calories
0         60     409.1
1         60     479.0
2         60     340.0
3         45     282.4
4         45     406.0
5         60     300.0
6         60     374.0
7         45     253.3
8         30     195.1
9         60     269.0
10        60     329.3
11        60     250.7
13        60     345.3
14        60     379.3
15        60     275.0
16        60     215.2
17        60     300.0
18        45       NaN
19        60     323.0
20        45     243.0
21        60     364.2
23        60     300.0
24        45     246.0
25        60     334.5
26        60     250.0
27        60     241.0
28        60       NaN
29        60     280.0
30        60     380.3
31        60     243.0

# 4️⃣ Data Analysis Tasks
23. Average Pulse

In [24]:
df["Pulse"].mean()

np.float64(103.73333333333333)

24. Day with highest Calories

In [25]:
df.loc[df["Calories"].idxmax()]

Duration                     60
Date        2020-12-02 00:00:00
Pulse                       117
Maxpulse                    145
Calories                  479.0
Name: 1, dtype: object

25. Total Calories in December

In [26]:
dec_total = df[df["Date"].dt.month == 12]["Calories"].sum()
dec_total

np.float64(8607.699999999999)

26. Average Duration

In [27]:
df["Duration"].mean()

np.float64(56.0)

27. Maximum Maxpulse

In [28]:
df["Maxpulse"].max()

np.int64(175)

# 5️⃣ Sorting & Grouping
29. Sort by Calories (descending)

In [29]:
df.sort_values(by="Calories", ascending=False)

    Duration       Date  Pulse  Maxpulse  Calories
1         60 2020-12-02    117       145     479.0
0         60 2020-12-01    110       130     409.1
4         45 2020-12-05    117       148     406.0
30        60 2020-12-30    102       129     380.3
14        60 2020-12-14    104       132     379.3
6         60 2020-12-07    110       136     374.0
21        60 2020-12-21    108       131     364.2
13        60 2020-12-13    106       128     345.3
2         60 2020-12-03    103       135     340.0
25        60 2020-12-25    102       126     334.5
10        60 2020-12-11    103       147     329.3
19        60 2020-12-19    103       123     323.0
17        60 2020-12-17    100       120     300.0
5         60 2020-12-06    102       127     300.0
23        60 2020-12-23    130       101     300.0
3         45 2020-12-04    109       175     282.4
29        60 2020-12-29    100       132     280.0
15        60 2020-12-15     98       123     275.0
9         60 2020-12-10     98       124     269.0
7         45 2020-12-08    104       134     253.3
11        60 2020-12-12    100       120     250.7
26        60 2020-12-26    100       120     250.0
24        45 2020-12-24    105       132     246.0
31        60 2020-12-31     92       115     243.0
20        45 2020-12-20     97       125     243.0
27        60 2020-12-27     92       118     241.0
16        60 2020-12-16     98       120     215.2
8         30 2020-12-09    109       133     195.1
18        45 2020-12-18     90       112       NaN
28        60 2020-12-28    103       132       NaN

30. Sort by Pulse (ascending)

In [30]:
df.sort_values(by="Pulse")

    Duration       Date  Pulse  Maxpulse  Calories
18        45 2020-12-18     90       112       NaN
27        60 2020-12-27     92       118     241.0
31        60 2020-12-31     92       115     243.0
20        45 2020-12-20     97       125     243.0
16        60 2020-12-16     98       120     215.2
15        60 2020-12-15     98       123     275.0
9         60 2020-12-10     98       124     269.0
11        60 2020-12-12    100       120     250.7
29        60 2020-12-29    100       132     280.0
17        60 2020-12-17    100       120     300.0
26        60 2020-12-26    100       120     250.0
25        60 2020-12-25    102       126     334.5
5         60 2020-12-06    102       127     300.0
30        60 2020-12-30    102       129     380.3
10        60 2020-12-11    103       147     329.3
2         60 2020-12-03    103       135     340.0
19        60 2020-12-19    103       123     323.0
28        60 2020-12-28    103       132       NaN
7         45 2020-12-08    104       134     253.3
14        60 2020-12-14    104       132     379.3
24        45 2020-12-24    105       132     246.0
13        60 2020-12-13    106       128     345.3
21        60 2020-12-21    108       131     364.2
3         45 2020-12-04    109       175     282.4
8         30 2020-12-09    109       133     195.1
0         60 2020-12-01    110       130     409.1
6         60 2020-12-07    110       136     374.0
4         45 2020-12-05    117       148     406.0
1         60 2020-12-02    117       145     479.0
23        60 2020-12-23    130       101     300.0

31. Group by Duration and average Pulse

In [31]:
df.groupby("Duration")["Pulse"].mean()

Duration
30    109.000000
45    103.666667
60    103.521739
Name: Pulse, dtype: float64

32. Top 5 workouts with highest Calories

In [32]:
df.nlargest(5, "Calories")

    Duration       Date  Pulse  Maxpulse  Calories
1         60 2020-12-02    117       145     479.0
0         60 2020-12-01    110       130     409.1
4         45 2020-12-05    117       148     406.0
30        60 2020-12-30    102       129     380.3
14        60 2020-12-14    104       132     379.3

# Sorting and Ranking
33. Sort dataset by Calories burned (ascending)

In [33]:
df.sort_values(by="Calories", ascending=True)

    Duration       Date  Pulse  Maxpulse  Calories
8         30 2020-12-09    109       133     195.1
16        60 2020-12-16     98       120     215.2
27        60 2020-12-27     92       118     241.0
20        45 2020-12-20     97       125     243.0
31        60 2020-12-31     92       115     243.0
24        45 2020-12-24    105       132     246.0
26        60 2020-12-26    100       120     250.0
11        60 2020-12-12    100       120     250.7
7         45 2020-12-08    104       134     253.3
9         60 2020-12-10     98       124     269.0
15        60 2020-12-15     98       123     275.0
29        60 2020-12-29    100       132     280.0
3         45 2020-12-04    109       175     282.4
23        60 2020-12-23    130       101     300.0
17        60 2020-12-17    100       120     300.0
5         60 2020-12-06    102       127     300.0
19        60 2020-12-19    103       123     323.0
10        60 2020-12-11    103       147     329.3
25        60 2020-12-25    102       126     334.5
2         60 2020-12-03    103       135     340.0
13        60 2020-12-13    106       128     345.3
21        60 2020-12-21    108       131     364.2
6         60 2020-12-07    110       136     374.0
14        60 2020-12-14    104       132     379.3
30        60 2020-12-30    102       129     380.3
4         45 2020-12-05    117       148     406.0
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
18        45 2020-12-18     90       112       NaN
28        60 2020-12-28    103       132       NaN

34. Sort dataset by Pulse (descending)

In [34]:
df.sort_values(by="Pulse", ascending=False)

    Duration       Date  Pulse  Maxpulse  Calories
23        60 2020-12-23    130       101     300.0
1         60 2020-12-02    117       145     479.0
4         45 2020-12-05    117       148     406.0
0         60 2020-12-01    110       130     409.1
6         60 2020-12-07    110       136     374.0
8         30 2020-12-09    109       133     195.1
3         45 2020-12-04    109       175     282.4
21        60 2020-12-21    108       131     364.2
13        60 2020-12-13    106       128     345.3
24        45 2020-12-24    105       132     246.0
14        60 2020-12-14    104       132     379.3
7         45 2020-12-08    104       134     253.3
10        60 2020-12-11    103       147     329.3
2         60 2020-12-03    103       135     340.0
28        60 2020-12-28    103       132       NaN
19        60 2020-12-19    103       123     323.0
5         60 2020-12-06    102       127     300.0
30        60 2020-12-30    102       129     380.3
25        60 2020-12-25    102       126     334.5
11        60 2020-12-12    100       120     250.7
29        60 2020-12-29    100       132     280.0
17        60 2020-12-17    100       120     300.0
26        60 2020-12-26    100       120     250.0
9         60 2020-12-10     98       124     269.0
16        60 2020-12-16     98       120     215.2
15        60 2020-12-15     98       123     275.0
20        45 2020-12-20     97       125     243.0
27        60 2020-12-27     92       118     241.0
31        60 2020-12-31     92       115     243.0
18        45 2020-12-18     90       112       NaN

35. Display top 5 highest calorie-burning workouts

In [35]:
df.nlargest(5, "Calories")

    Duration       Date  Pulse  Maxpulse  Calories
1         60 2020-12-02    117       145     479.0
0         60 2020-12-01    110       130     409.1
4         45 2020-12-05    117       148     406.0
30        60 2020-12-30    102       129     380.3
14        60 2020-12-14    104       132     379.3

36. Display top 5 longest workouts

In [36]:
df.nlargest(5, "Duration")

   Duration       Date  Pulse  Maxpulse  Calories
0        60 2020-12-01    110       130     409.1
1        60 2020-12-02    117       145     479.0
2        60 2020-12-03    103       135     340.0
5        60 2020-12-06    102       127     300.0
6        60 2020-12-07    110       136     374.0

37. Rank workouts based on Calories burned

In [37]:
df["Calorie_Rank"] = df["Calories"].rank(ascending=False)

# Aggregation and Statistics
38. Calculate average Pulse

In [38]:
df["Pulse"].mean()

np.float64(103.73333333333333)

39. Calculate average Duration

In [39]:
df["Duration"].mean()

np.float64(56.0)

40. Find maximum Calories burned

In [40]:
df["Calories"].max()

np.float64(479.0)

41. Find minimum Pulse

In [41]:
df["Pulse"].min()

np.int64(90)

42. Find total Calories burned

In [42]:
df["Calories"].sum()

np.float64(8607.699999999999)

43. Count how many workouts have Duration = 60

In [43]:
df[df["Duration"] == 60].shape[0]

23

# GroupBy Operations
44. Group dataset by Duration and calculate average Calories

In [44]:
df.groupby("Duration")["Calories"].mean()

Duration
30    195.100000
45    286.140000
60    317.359091
Name: Calories, dtype: float64

45. Group by Duration and calculate average Pulse

In [45]:
df.groupby("Duration")["Pulse"].mean()

Duration
30    109.000000
45    103.666667
60    103.521739
Name: Pulse, dtype: float64

46. Find maximum Pulse for each Duration group

In [46]:
df.groupby("Duration")["Pulse"].max()

Duration
30    109
45    117
60    130
Name: Pulse, dtype: int64

47. Count number of workouts per Duration category

In [47]:
df.groupby("Duration").size()

Duration
30     1
45     6
60    23
dtype: int64

##                                                  Mini Project Challenge
1. Clean the dataset

In [48]:
df["Date"] = pd.to_datetime(df["Date"], format="mixed", errors="coerce")
df["Calories"].fillna(df["Calories"].mean(), inplace=True)
df.drop_duplicates(inplace=True)
df.dropna(subset=["Date"], inplace=True)

C:\Users\DELL\AppData\Local\Temp\ipykernel_10648\2398065990.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Calories"].fillna(df["Calories"].mean(), inplace=True)

2. Which day had the highest calorie burn?

In [49]:
df.loc[df["Calories"].idxmax()]

Duration                         60
Date            2020-12-02 00:00:00
Pulse                           117
Maxpulse                        145
Calories                      479.0
Calorie_Rank                    1.0
Name: 1, dtype: object

3. What is the average workout duration?

In [50]:
df["Duration"].mean()

np.float64(56.0)

4. Which workout had the highest Pulse rate?

In [51]:
df.loc[df["Pulse"].idxmax()]

Duration                         60
Date            2020-12-23 00:00:00
Pulse                           130
Maxpulse                        101
Calories                      300.0
Calorie_Rank                   14.0
Name: 23, dtype: object

5. Average Calories burned per minute

In [52]:
(df["Calories"] / df["Duration"]).mean()

np.float64(5.5236309523809535)